---

- name: Create database
  become: yes
  become_user: postgres
  postgresql_db:
    name: mastodon
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8

- name: Create database user
  become: yes
  become_user: postgres
  postgresql_user:
    name: mastodon
    db: mastodon

- name: Assign privileges
  become: yes
  become_user: postgres
  postgresql_privs:
    db: mastodon
    role: mastodon
    type: database
    privs: ALL
