---

- name: Remove default
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: Create dhparams
  openssl_dhparam:
    path: /etc/ssl/private/dhparams.pem
    size: 4096

- name: Copy config
  template:
    src: mastodon.conf.j2
    dest: /etc/nginx/sites-available/mastodon.conf

- name: Enable config
  file:
    src: /etc/nginx/sites-available/mastodon.conf
    dest: /etc/nginx/sites-enabled/mastodon.conf
    state: link

- name: Enable nginx
  service:
    name: nginx
    enabled: yes

- name: Stop for letsencrypt
  service:
    name: nginx
    state: stopped
  when: not mastodon_upgrade|bool

- name: Create letsencrypt certificate
  shell: letsencrypt certonly -n --standalone -m {{ letsencrypt_email }} --agree-tos -d {{ mastodon_public_hostname }}
  args:
    creates: /etc/letsencrypt/live/{{ mastodon_public_hostname }}
  when: not mastodon_upgrade|bool

- name: Start nginx again
  service:
    name: nginx
    state: started
  when: not mastodon_upgrade|bool

- name: Disable (legacy) LE cron job
  cron:
    name: renew_letsencrypt
    special_time: weekly
    job: letsencrypt --renew certonly -n --webroot -w /home/mastodon/live/public -m {{ letsencrypt_email }} --agree-tos -d {{ mastodon_public_hostname }} && systemctl reload nginx
    state: absent # remove legacy job

- name: Add certbot post hook
  copy:
    src: reload-nginx
    dest: /etc/letsencrypt/renewal-hooks/post/reload-nginx
    mode: 0755
