---

- name: Update apt cache and distribution
  apt:
    update_cache: true
    upgrade: dist

- name: Install Docker deployment dependencies
  apt:
    state: present
    pkg:
      - ca-certificates
      - certbot
      - curl
      - docker.io
      - docker-compose-v2
      - nginx
      - openssl
      - postgresql-client
      - python3-docker
      - rsync
      - ufw

- name: Enable Docker
  service:
    name: docker
    enabled: true
    state: started
