---

# add node repository key

- name: add node repo key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

# register node repository

- name: add node repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_20.x jammy main

# add yarn repository key

- name: remove yarn repo key
  apt_key:
    id: "72ECF46A56B4AD39C907BBB71646B01B86E50310"
    state: absent

# register yarn repository

- name: remove yarn repository
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian stable main
    state: absent

# add postgres repository key

- name: add postgres repo key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

# add postgres repository

- name: add postgres repository
  apt_repository:
    repo: deb https://apt.postgresql.org/pub/repos/apt jammy-pgdg main

# update cache

- name: update cache and distribution
  apt:
    update_cache: true
    upgrade: dist

# remove classic yarn
- name: remove classic yarn
  apt:
    state: absent
    pkg:
      - yarn

- name: remove classic yarn (npm)
  community.general.npm:
    name: yarn
    global: true
    state: absent

# install packages

- name: install dependencies
  apt:
    state: present
    pkg:
    - python3-psycopg2
    - curl
    - imagemagick
    - ffmpeg
    - libpq-dev
    - libxml2-dev
    - libxslt1-dev
    - file
    - git-core
    - g++
    - libprotobuf-dev
    - protobuf-compiler
    - pkg-config
    - nodejs
    - gcc
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm-dev
    - nginx
    - redis-server
    - redis-tools
    - postgresql
    - postgresql-contrib
    - certbot
    - libidn11-dev
    - libicu-dev
    - libjemalloc-dev

- name: enable corepack
  ansible.builtin.command: corepack enable
