
---

- name: Install Ruby
  include_role:
    name: zzet.rbenv
  vars:
    rbenv:
      env: system
      version: v1.2.0
      default_ruby: "{{ruby_version}}"
      rubies:
      - version: "{{ruby_version}}"

- name: Install bundler
  command: gem install bundler
  args:
    creates: /usr/local/rbenv/shims/bundler
