
---

- name: Install Ruby
  include_role:
    name: zzet.rbenv
  vars:
    rbenv:
      env: system
      version: v1.1.2
      default_ruby: 2.6.5
      rubies:
      - version: 2.6.5

- name: Install bundler
  command: gem install bundler
  args:
    creates: /usr/local/rbenv/shims/bundler
